langauage: generic
sudo: required
serivces:
  - docker
before_install:
  - docker build -t nasserheydari/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true nasserheydari/docker-react npm run test
  
